#pragma once
#include "minidriver.h"
#include "permission.h"

typedef struct _VolumeList
{
	//
	// list entry member
	//
	LIST_ENTRY list;

	/************************************************************************/
	/* our member                                                                     */
	/************************************************************************/
	//
	// volume guid
	//
	UNICODE_STRING GUID;
	WCHAR _GUID_Buffer[GUID_SIZE];

	//
	//  Types
	//  The possible DeviceCharacteristics flags are defined in NTIFS.H.
	//  Potential values are:
	//      FILE_REMOVABLE_MEDIA
	//      FILE_READ_ONLY_DEVICE
	//      FILE_FLOPPY_DISKETTE
	//      FILE_WRITE_ONCE_MEDIA
	//      FILE_REMOTE_DEVICE
	//      FILE_DEVICE_IS_MOUNTED
	//      FILE_VIRTUAL_VOLUME
	//      FILE_AUTOGENERATED_DEVICE_NAME
	//      FILE_DEVICE_SECURE_OPEN
	//
	ULONG	type;

	//
	// use key install on this volume
	//
	UserKey	key;
	BOOL		isHasUser;
}VolumeList, *PVolumeList;

#define FLT_TAG 'Fttg'

typedef enum {
	MsgCode_Null, // null define , for daemon use

	// user
	MsgCode_User_Query,
	MsgCode_User_Login,
	MsgCode_User_Registry,
	MsgCode_User_Logout,

	// file
	MsgCode_Permission_Get,
	MsgCode_Permission_Set,

	// driver
	MsgCode_GetPause,
	MsgCode_SetPause,
}MsgCode, *PMsgCode;

typedef struct
{
	WCHAR  name[PM_NAME_MAX];		// user name
	WCHAR  group[PM_NAME_MAX];		// group name
	WCHAR  password[PM_NAME_MAX];	// password
	WCHAR  volume[GUID_SIZE];		// volume guid
}Msg_User_Registry, *PMsg_User_Registry;

typedef struct
{
	PWCHAR path;					// file path
	PermissionCode pmCode;		// permission code
}Msg_File, *PMsg_File;

//
// user filter interface 
//
NTSTATUS oninit(PUNICODE_STRING _regPath);	// call when dirver start
void onexit();		// call when dirver unload
NTSTATUS onstart(PVolumeContext ctx); // call when setup filter on volume
void onstop(PVolumeContext ctx);		// call when stop filter on volme
NTSTATUS onfilter(PFLT_FILE_NAME_INFORMATION info, PUNICODE_STRING guid);// call when filter data on volme
NTSTATUS onmsg(MsgCode msg, PVOID buffer, ULONG size, PULONG retlen);	// call when user application message in
NTSTATUS sendMsg(MsgCode msg);	// send message to user application
