#pragma once
#include "minidriver.h"
#include "permission.h"
#include "msg.h"

typedef struct _VolumeList
{
	//
	// list entry member
	//
	LIST_ENTRY list;

	/************************************************************************/
	/* our member                                                                     */
	/************************************************************************/
	//
	// volume guid
	//
	UNICODE_STRING GUID;
	WCHAR _GUID_Buffer[GUID_SIZE];

	//
	// instance
	//
	PFLT_INSTANCE instance;

	//
	// volume letter
	//
	WCHAR letter;

	//
	//  Types
	//  The possible DeviceCharacteristics flags are defined in NTIFS.H.
	//  Potential values are:
	//      FILE_REMOVABLE_MEDIA
	//      FILE_READ_ONLY_DEVICE
	//      FILE_FLOPPY_DISKETTE
	//      FILE_WRITE_ONCE_MEDIA
	//      FILE_REMOTE_DEVICE
	//      FILE_DEVICE_IS_MOUNTED
	//      FILE_VIRTUAL_VOLUME
	//      FILE_AUTOGENERATED_DEVICE_NAME
	//      FILE_DEVICE_SECURE_OPEN
	//
	ULONG	type;

	//
	// use key install on this volume
	//
	UserKey	key;

	//
	// volume state: (N:normal, W:work root, U:has user, K:user login root) 
	//
	WCHAR state;
}VolumeList, *PVolumeList;


#define vl_isWorkRoot(vl) ((vl)->state == L'W')
#define vl_setWorkRoot(vl) ((vl)->state = L'W')

#define vl_isKeyRoot(vl) ((vl)->state == L'K')
#define vl_setKeyRoot(vl) ((vl)->state = L'K')

#define vl_ishasUser(vl) ((vl)->state == L'U')
#define vl_sethasUser(vl) ((vl)->state = L'U')


#define FLT_TAG 'Fttg'

//
// user filter interface 
//
NTSTATUS oninit(PUNICODE_STRING _regPath);	// call when dirver start
void onexit();		// call when dirver unload
NTSTATUS onstart(PVolumeContext ctx, PFLT_INSTANCE instance); // call when setup filter on volume
void onstop(PVolumeContext ctx);		// call when stop filter on volme
NTSTATUS onfilter(PFLT_FILE_NAME_INFORMATION info, PUNICODE_STRING guid);// call when filter data on volme
NTSTATUS onmsg(MsgCode msg, PVOID buffer, ULONG size, PULONG retlen);	// call when user application message in
NTSTATUS sendMsg(MsgCode msg);	// send message to user application
