//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fcapi_wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fcapi_wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close program!.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User:.
        /// </summary>
        public static string del_user {
            get {
                return ResourceManager.GetString("del_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver is not installed!.
        /// </summary>
        public static string driver_no_install {
            get {
                return ResourceManager.GetString("driver_no_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver must be loaded!.
        /// </summary>
        public static string driver_no_run {
            get {
                return ResourceManager.GetString("driver_no_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No found!.
        /// </summary>
        public static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail!.
        /// </summary>
        public static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        public static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed!.
        /// </summary>
        public static string login_fail {
            get {
                return ResourceManager.GetString("login_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User:.
        /// </summary>
        public static string new_user {
            get {
                return ResourceManager.GetString("new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User no found!.
        /// </summary>
        public static string no_user {
            get {
                return ResourceManager.GetString("no_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Root no set!.
        /// </summary>
        public static string no_work_dir {
            get {
                return ResourceManager.GetString("no_work_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid!.
        /// </summary>
        public static string null_password {
            get {
                return ResourceManager.GetString("null_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK！.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Failed!.
        /// </summary>
        public static string open_fail {
            get {
                return ResourceManager.GetString("open_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Success!.
        /// </summary>
        public static string open_success {
            get {
                return ResourceManager.GetString("open_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(R).
        /// </summary>
        public static string pm_name_0 {
            get {
                return ResourceManager.GetString("pm_name_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(W).
        /// </summary>
        public static string pm_name_1 {
            get {
                return ResourceManager.GetString("pm_name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group(R).
        /// </summary>
        public static string pm_name_2 {
            get {
                return ResourceManager.GetString("pm_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group(W).
        /// </summary>
        public static string pm_name_3 {
            get {
                return ResourceManager.GetString("pm_name_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othe(R).
        /// </summary>
        public static string pm_name_4 {
            get {
                return ResourceManager.GetString("pm_name_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other(W).
        /// </summary>
        public static string pm_name_5 {
            get {
                return ResourceManager.GetString("pm_name_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Root:.
        /// </summary>
        public static string work_root {
            get {
                return ResourceManager.GetString("work_root", resourceCulture);
            }
        }
    }
}
